### ISSUE TITLE
Analysis of EDZ format

### ISSUE THREAD

**Issue by mrentsch65** [FabianSig/TINF22F_Team4_EDZ_Viewer_and_Converter#44]
Da sollten Sie bis zur Präsentation am 10.11. getan haben und in der SRS rudimentär die Spezifika der EDZ beschreiben!
Nehmen Sie dazu am Besten ein einfaches Kabelmodell, um in das Thema hineinzukommen:
https://dataportal.eplan.com/part-details/Murrelektronik/MURR.7000-40041-5770150/id-1490243?search=MURR.7000-40041%205770150&page=1
Sie können die Datei hier herunterladen und mit einem ZIP-Programm entpacken: https://nextcloud.dhbw-stuttgart.de/index.php/f/26107880

Und dann hier ein komplexeres Modell mit einer internen Verdrahtung:
https://dataportal.eplan.com/part-details/Murrelektronik/MURR.7000-88601-0000000/id-1687784?search=MURR.7000-&page=1

Hier in der "Download"-Sektion die Datei dazu: https://shop.murrelektronik.com/7000-88601-0000000/
![image](https://github.com/FabianSig/TINF22F_Team4_EDZ_Viewer_and_Converter/assets/50681355/4a23e837-8d49-49c9-8fec-dd8d539ea3bc)

**Comment by mrentsch65** [comment]
Sie haben dieses Issue completed, aber nicht beschrieben, was Sie getan haben?

**Comment by FabianSig** [comment]
> Sie haben dieses Issue completed, aber nicht beschrieben, was Sie getan haben?

Im Wiki wurde die Analyse des EDZ Formats im Allgemeinen und anhand eines Beispiels hinzugefügt.
